
all:
	vcs +v2k async_fifo_in_144b_out_72b.v async_fifo_in_72b_out_144b.v fallthrough_small_fifo.v fifo_ddr2_blk_rdwr_64b_2_72b.v fifo_ddr2_blk_rdwr_72b_2_64b.v small_async_fifo.v ddr2_blk_rdwr.v dram_ctrl.v tail_cache.v tail_cache_arb.v head_cache.v head_cache_arb.v dram_output_queues.v


clean:
	rm -rf csrc simv *~

