#!/usr/bin/perl

use Getopt::Long;
use NF::TestLib;

open CPUHW, "$ENV{'NF_ROOT'}/projects/scone/sw/cpuhw";
while (<CPUHW>) {
	chomp;

	# Work out the port and IP address
	/^eth(\d)\s+(\d+\.\d+\.\d+\.\d+)/;

	# Run ifconfig
	`/sbin/ifconfig nf2c$1 $2 up`;
}
