#
# $Id:
#

# Set the location for SBIN files
SBINDIR ?= /usr/local/sbin

# Install the various files
all:

# Install the various files
install:
	install cpci_reprogram.pl $(SBINDIR)

clean:

.PHONY: all install clean
