#!/bin/env python

from NFTestLib import *
from NFTestHeader import reg_defines, scapy
from PacketLib import *

import random

from RegressRouterLib import *

interfaces = ("nf2c0", "nf2c1", "nf2c2", "nf2c3", "eth1", "eth2")

nftest_init(interfaces, 'conn')
nftest_start()

nftest_barrier()

routerMAC0 = "00:ca:fe:00:00:01"
routerMAC1 = "00:ca:fe:00:00:02"
routerMAC2 = "00:ca:fe:00:00:03"
routerMAC3 = "00:ca:fe:00:00:04"

routerIP0 = "192.168.0.40"
routerIP1 = "192.168.1.40"
routerIP2 = "192.168.2.40"
routerIP3 = "192.168.3.40"

dstIP0 = "192.168.0.50"
dstIP1 = "192.168.1.50"
dstIP2 = "192.168.2.50"
dstIP3 = "192.168.3.50"

dstMAC0 = "aa:bb:cc:dd:ee:01"
dstMAC1 = "aa:bb:cc:dd:ee:02"
dstMAC2 = "aa:bb:cc:dd:ee:03"
dstMAC3 = "aa:bb:cc:dd:ee:04"

ALLSPFRouters = "224.0.0.5"

# Write the mac and IP addresses
nftest_add_dst_ip_filter_entry ('nf2c0', 0, routerIP0)
nftest_add_dst_ip_filter_entry ('nf2c1', 1, routerIP1)
nftest_add_dst_ip_filter_entry ('nf2c2', 2, routerIP2)
nftest_add_dst_ip_filter_entry ('nf2c3', 3, routerIP3)
nftest_add_dst_ip_filter_entry ('nf2c0', 4, ALLSPFRouters)

nftest_set_router_MAC ('nf2c0', routerMAC0)
nftest_set_router_MAC ('nf2c1', routerMAC1)
nftest_set_router_MAC ('nf2c2', routerMAC2)
nftest_set_router_MAC ('nf2c3', routerMAC3)

if isHW():
    nftest_regread_expect(reg_defines.MDIO_PHY_0_CONTROL_REG(), 0x1140)
    nftest_regread_expect(reg_defines.MDIO_PHY_1_CONTROL_REG(), 0x1140)
    nftest_regread_expect(reg_defines.MDIO_PHY_2_CONTROL_REG(), 0x5140)
    nftest_regread_expect(reg_defines.MDIO_PHY_3_CONTROL_REG(), 0x5140)

NUM_PKTS = 20

# add destinations to be filtered to the software
nftest_add_dst_ip_filter_entry ('nf2c0', 5, dstIP0)
nftest_add_dst_ip_filter_entry ('nf2c0', 6, dstIP1)
nftest_add_dst_ip_filter_entry ('nf2c0', 7, dstIP2)

nftest_regwrite(reg_defines.ROUTER_OP_LUT_NUM_FILTERED_PKTS_REG(), 0)

nftest_barrier()

ippkt_hdr = make_MAC_hdr(dst_MAC=routerMAC0,
                         src_MAC=dstMAC3)/make_IP_hdr(src_IP=dstIP3,
                                                      dst_IP=dstIP0, ttl=64)

precreated0 = []
load0 = []
ippkt_hdr[scapy.Ether].dst = routerMAC0
for i in range(NUM_PKTS):
    whichIP = random.randint(0,2)
    if whichIP == 0:
        ippkt_hdr[scapy.IP].dst = dstIP0
    elif whichIP == 1:
        ippkt_hdr[scapy.IP].dst = dstIP1
    else:
        ippkt_hdr[scapy.IP].dst = dstIP2
    load = generate_load(random.randint(60-len(ippkt_hdr), 1514-len(ippkt_hdr)))
    load0.append(load)
    precreated0.append(ippkt_hdr/load)

precreated1 = []
load1 = []
ippkt_hdr[scapy.Ether].dst = routerMAC1
for i in range(NUM_PKTS):
    whichIP = random.randint(0,2)
    if whichIP == 0:
        ippkt_hdr[scapy.IP].dst = dstIP0
    elif whichIP == 1:
        ippkt_hdr[scapy.IP].dst = dstIP1
    else:
        ippkt_hdr[scapy.IP].dst = dstIP2
    load = generate_load(random.randint(60-len(ippkt_hdr), 1514-len(ippkt_hdr)))
    load1.append(load)
    precreated1.append(ippkt_hdr/load)

exp_hdr = ippkt_hdr
exp_hdr[scapy.Ether].dst = dstMAC0
exp_hdr[scapy.Ether].src = routerMAC1
exp_hdr[scapy.IP].dst = dstIP0
exp_hdr[scapy.IP].ttl = 63

expected0 = [exp_hdr/x.load for x in precreated0]
expected1 = [exp_hdr/x.load for x in precreated1]

for i in range(NUM_PKTS):
    pkt = precreated0[i]
    nftest_send_phy('nf2c0', pkt)
    nftest_expect_dma('nf2c0', pkt)

    pkt = precreated1[i]
    nftest_send_phy('nf2c1', pkt)
    nftest_expect_dma('nf2c1', pkt)

nftest_barrier()

nftest_regread_expect(reg_defines.ROUTER_OP_LUT_NUM_FILTERED_PKTS_REG(), 2*NUM_PKTS)

nftest_invalidate_dst_ip_filter_entry('nf2c0', 5)
nftest_add_LPM_table_entry('nf2c0', 0, dstIP0, "255.255.255.0", "0.0.0.0", 0x04) # send out MAC1
nftest_add_ARP_table_entry('nf2c0', 0, dstIP0, dstMAC0)

nftest_barrier()

for i in range(NUM_PKTS):
    pkt = precreated0[i]
    nftest_send_phy('nf2c0', pkt)
    if pkt[scapy.IP].dst == dstIP0:
        nftest_expect_phy('nf2c1', expected0[i])
    else:
        nftest_expect_dma('nf2c0', pkt)

    pkt = precreated1[i]
    nftest_send_phy('nf2c1', pkt)
    if pkt[scapy.IP].dst == dstIP0:
        nftest_expect_phy('nf2c1', expected1[i])
    else:
        nftest_expect_dma('nf2c1', pkt)

nftest_barrier()

nftest_invalidate_LPM_table_entry('nf2c0', 0)
nftest_invalidate_ARP_table_entry('nf2c0', 0)

nftest_barrier()

total_errors = nftest_finish()

if total_errors == 0:
    print 'SUCCESS!'
    sys.exit(0)
else:
    print 'FAIL: ' + str(total_errors) + ' errors'
    sys.exit(1)
