#!/bin/env python

from NFTestLib import *
from NFTestHeader import reg_defines, scapy
from PacketLib import *

import random

from RegressRouterLib import *

interfaces = ("nf2c0", "nf2c1", "nf2c2", "nf2c3", "eth1", "eth2")

nftest_init(interfaces, 'conn')
nftest_start()

nftest_barrier()

routerMAC0 = "00:ca:fe:00:00:01"
routerMAC1 = "00:ca:fe:00:00:02"
routerMAC2 = "00:ca:fe:00:00:03"
routerMAC3 = "00:ca:fe:00:00:04"

routerIP0 = "192.168.0.40"
routerIP1 = "192.168.1.40"
routerIP2 = "192.168.2.40"
routerIP3 = "192.168.3.40"

# Write the mac and IP addresses
nftest_add_dst_ip_filter_entry ('nf2c0', 0, routerIP0)
nftest_add_dst_ip_filter_entry ('nf2c1', 1, routerIP1)
nftest_add_dst_ip_filter_entry ('nf2c2', 2, routerIP2)
nftest_add_dst_ip_filter_entry ('nf2c3', 3, routerIP3)

nftest_set_router_MAC ('nf2c0', routerMAC0)
nftest_set_router_MAC ('nf2c1', routerMAC1)
nftest_set_router_MAC ('nf2c2', routerMAC2)
nftest_set_router_MAC ('nf2c3', routerMAC3)

for i in range(32):
    nftest_invalidate_LPM_table_entry('nf2c0', i)

for i in range(32):
    nftest_invalidate_ARP_table_entry('nf2c0', i)


index = 0
subnetIP = "192.168.1.0"
subnetIP2 = "192.168.1.1"
subnetMask = "255.255.255.0"
subnetMask2 = "255.255.255.225"
nextHopIP = "192.168.1.54"
nextHopIP2 = "192.168.3.12"
outPort = 0x1
outPort2 = 0x4
nextHopMAC = "dd:55:dd:66:dd:77"

nftest_add_LPM_table_entry('nf2c0', 1, subnetIP, subnetMask, nextHopIP, outPort)

nftest_add_LPM_table_entry('nf2c0', 0, subnetIP2, subnetMask2, nextHopIP2, outPort2)

nftest_add_ARP_table_entry('nf2c0', index, nextHopIP, nextHopMAC)

nftest_add_ARP_table_entry('nf2c0', index, nextHopIP2, nextHopMAC)

nftest_barrier()

total_errors = 0

pkts = []
exp_pkts = []
for i in range(100):
    hdr = make_MAC_hdr(src_MAC="aa:bb:cc:dd:ee:ff", dst_MAC=routerMAC0,
                       EtherType=0x800)/scapy.IP(src="192.168.0.1",
                                                 dst="192.168.1.1", ttl=64)
    exp_hdr = make_MAC_hdr(src_MAC=routerMAC1, dst_MAC=nextHopMAC,
                           EtherType=0x800)/scapy.IP(src="192.168.0.1",
                                                     dst="192.168.1.1", ttl=63)
    load = generate_load(100)
    pkt = hdr/load
    exp_pkt = exp_hdr/load

    pkts.append(pkt)
    exp_pkts.append(exp_pkt)

for i in range(100):
    nftest_send_phy('nf2c0', pkts[i])
    nftest_expect_phy('nf2c1', exp_pkts[i])

nftest_barrier()

total_errors += nftest_finish()

if total_errors == 0:
    print 'SUCCESS!'
    sys.exit(0)
else:
    print 'FAIL: ' + str(total_errors) + ' errors'
    sys.exit(1)
