#
# $Id:
#

# Set the location for SBIN files
SBINDIR ?= /usr/local/sbin

# Install the various files
all:

install:
	install dumpregs.sh $(SBINDIR)
	install loadregs.sh $(SBINDIR)

clean:

.PHONY: all install clean
