#!/bin/sh
# Restore the IP Forwarding setting after running the test

TMP_FILE="/tmp/ip_forward_bak"
IP_FWD="/proc/sys/net/ipv4/ip_forward"

# Restore the backed up value if it exists
if [ -f $TMP_FILE ]; then
	cat $TMP_FILE > $IP_FWD
	rm -f $TMP_FILE
fi
